#!/usr/bin/env python3
"""Render docs/latex_iclr/tables/retrieval_results_15k.tex.

Reports nDCG@10 on the five BEIR benchmarks that were run, plus their
unweighted mean. Distilled-student rows come from the three-seed retrieval
aggregate of the 15K main-results run; teacher and student-base rows come from
the untrained baseline sweep. Scores are printed as percentages with the sample
standard deviation over three seeds. Best / second-best among distilled
students is bold / underlined, matching Table~\\ref{tab:main-results}.
"""

from __future__ import annotations

import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
RETRIEVAL_CSV = (
    ROOT
    / "runs"
    / "main_results_talas15k_h200_gpu67_20260904-082000"
    / "all_pairs_retrieval_mean_std.csv"
)
BASELINE_CSV = (
    ROOT / "runs" / "aux_sweeps_20260904-113834" / "baseline" / "retrieval_summary.csv"
)
OUT_TEX = ROOT / "docs" / "latex_iclr" / "tables" / "retrieval_results_15k.tex"

BENCHMARKS = ("arguana", "scifact", "scidocs", "nfcorpus", "fiqa", "AVG")
BENCHMARK_LABELS = (
    "ArguAna",
    "SciFact",
    "SciDocs",
    "NFCorpus",
    "FiQA-2018",
    "Avg.",
)
# The two sources spell the mean row differently.
BASELINE_BENCHMARKS = ("arguana", "scifact", "scidocs", "nfcorpus", "fiqa", "average")
METRIC = "ndcg_at_10"

# (pair key, panel caption, teacher model id, student-base model id)
PAIRS = (
    (
        "qwen3_4b_to_bert_base",
        r"(a) Qwen3-Embedding-4B $\rightarrow$ BERT-base (109M)",
        "Qwen/Qwen3-Embedding-4B",
        "google-bert/bert-base-uncased",
    ),
    (
        "bge_m3_to_minilm_h768",
        r"(b) BGE-M3 $\rightarrow$ MiniLMv2-H768 (66M)",
        "BAAI/bge-m3",
        "nreimers/MiniLMv2-L6-H768-distilled-from-BERT-Base",
    ),
    (
        "qwen3_0.6b_to_minilm_h384",
        r"(c) Qwen3-Embedding-0.6B $\rightarrow$ MiniLMv2-H384 (22M)",
        "Qwen/Qwen3-Embedding-0.6B",
        "nreimers/MiniLMv2-L6-H384-distilled-from-BERT-Base",
    ),
)

# (csv method key, row label)
METHODS = (
    ("rkd", "RKD"),
    ("stella", "Stella"),
    ("cdm", "CDM"),
    ("dskd", "DSKD"),
    ("emo", "EMO"),
    ("talas", "TALAS"),
    ("geoode", r"\textbf{GATE-KD}"),
)


def load_students() -> dict:
    out: dict = {}
    with RETRIEVAL_CSV.open(newline="") as handle:
        for row in csv.DictReader(handle):
            out[(row["pair"], row["method"], row["benchmark"])] = (
                float(row[f"{METRIC}_mean"]),
                float(row[f"{METRIC}_std"]),
            )
    return out


def load_baselines() -> dict:
    out: dict = {}
    with BASELINE_CSV.open(newline="") as handle:
        for row in csv.DictReader(handle):
            out[(row["model"], row["benchmark"])] = float(row[f"{METRIC}_mean"])
    return out


def emit_baseline(label: str, model: str, baselines: dict) -> str:
    cells = [
        f"{100 * baselines[(model, benchmark)]:.2f}"
        for benchmark in BASELINE_BENCHMARKS
    ]
    return f"        {label} & " + " & ".join(cells) + r" \\"


def emit_students(pair: str, students: dict) -> list[str]:
    # Rank each column across distilled students only.
    ranks = {
        benchmark: sorted(
            (m for m, _ in METHODS),
            key=lambda m: students[(pair, m, benchmark)][0],
            reverse=True,
        )[:2]
        for benchmark in BENCHMARKS
    }

    lines = []
    for method, label in METHODS:
        cells = []
        for benchmark in BENCHMARKS:
            mean, std = students[(pair, method, benchmark)]
            body = f"{100 * mean:.2f}"
            best, second = ranks[benchmark]
            if method == best:
                body = rf"\textbf{{{body}}}"
            elif method == second:
                body = rf"\underline{{{body}}}"
            cells.append(rf"\retmetric{{{body}}}{{{100 * std:.2f}}}")
        lines.append(f"        {label} & " + " & ".join(cells) + r" \\")
    return lines


def build() -> str:
    students = load_students()
    baselines = load_baselines()
    ncols = len(BENCHMARKS) + 1

    header = [
        "% Generated by scripts/figures/render_retrieval_15k.py -- do not edit by hand.",
        "% Distilled-student rows:",
        "% runs/main_results_talas15k_h200_gpu67_20260904-082000/"
        "all_pairs_retrieval_mean_std.csv.",
        "% Teacher and student-base rows:",
        "% runs/aux_sweeps_20260904-113834/baseline/retrieval_summary.csv.",
        r"\begin{table*}[t]",
        r"    \caption{\textbf{Zero-shot dense retrieval after 15K distillation"
        r" (nDCG@10).}",
        r"    Five BEIR benchmarks span argument retrieval (ArguAna), scientific",
        r"    claim--evidence retrieval (SciFact), citation prediction (SciDocs),",
        r"    biomedical retrieval (NFCorpus), and financial question answering",
        r"    (FiQA-2018); Avg.~is their unweighted mean.  Retrieval is evaluated with",
        r"    exhaustive cosine ranking, no instruction prefix, and no task-specific",
        r"    training.  Teacher and student-base scores are deterministic; distilled",
        r"    scores are mean $\pm$ sample standard deviation over three seeds.  Among",
        r"    distilled students, best and second-best results are shown in bold and",
        r"    underlined, respectively.  Recall@10 and MRR@10 are omitted for space;",
        r"    they agree with nDCG@10 on the top-ranked method in 17 of 18 columns (the",
        r"    exception is NFCorpus in configuration (b), where MRR@10 places RKD"
        r" first).",
        r"    Retrieval is reported separately and is not",
        r"    included in the sentence-level averages of Table~\ref{tab:main-results}.}",
        r"    \label{tab:retrieval-results-15k}",
        r"    \vspace{0.5em}",
        r"    \centering",
        r"    \footnotesize",
        r"    \setlength{\tabcolsep}{5pt}",
        r"    \renewcommand{\arraystretch}{1.08}",
        r"    \newcommand{\retmetric}[2]{#1{\tiny $\pm$ #2}}",
        r"    \begin{tabular}{@{}l" + "c" * len(BENCHMARKS) + r"@{}}",
        r"        \toprule",
        "        Method & " + " & ".join(BENCHMARK_LABELS) + r" \\",
    ]

    body: list[str] = []
    for pair, panel, teacher, student_base in PAIRS:
        body.append(r"        \midrule")
        body.append(
            rf"        \multicolumn{{{ncols}}}{{@{{}}c}}{{\textit{{{panel}}}}} \\"
        )
        body.append(r"        \midrule")
        body.append(emit_baseline("Teacher", teacher, baselines))
        body.append(emit_baseline("Student base", student_base, baselines))
        body.append(r"        \cmidrule(lr){1-%d}" % ncols)
        body.extend(emit_students(pair, students))

    footer = [
        r"        \bottomrule",
        r"    \end{tabular}",
        r"\end{table*}",
    ]

    return "\n".join([*header, *body, *footer]) + "\n"


if __name__ == "__main__":
    OUT_TEX.write_text(build())
    print(f"wrote {OUT_TEX.relative_to(ROOT)}")
