#!/usr/bin/env python3
"""Render docs/latex_iclr/tables/retrieval_results_15k.tex.

Reports nDCG@10 on the five BEIR benchmarks that were run, plus their
unweighted mean. Distilled-student rows come from the three-seed retrieval
aggregate of the 15K main-results run; teacher and student-base rows come from
the untrained baseline sweep. Scores are printed as percentages with the sample
standard deviation over three seeds. Best / second-best among distilled
students is bold / underlined, matching Table~\\ref{tab:main-results}.
"""

from __future__ import annotations

import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
RETRIEVAL_CSV = (
    ROOT
    / "runs"
    / "main_results_talas15k_h200_gpu67_20260904-082000"
    / "all_pairs_retrieval_mean_std.csv"
)
BASELINE_CSV = (
    ROOT / "runs" / "aux_sweeps_20260904-113834" / "baseline" / "retrieval_summary.csv"
)
OUT_TEX = ROOT / "docs" / "latex_iclr" / "tables" / "retrieval_results_15k.tex"

BENCHMARKS = ("arguana", "scifact", "scidocs", "nfcorpus", "fiqa", "AVG")
BENCHMARK_LABELS = (
    "ArguAna",
    "SciFact",
    "SciDocs",
    "NFCorpus",
    "FiQA-2018",
    "Avg.",
)
# The two sources spell the mean row differently.
BASELINE_BENCHMARKS = ("arguana", "scifact", "scidocs", "nfcorpus", "fiqa", "average")
METRIC = "ndcg_at_10"

# (pair key, panel caption, teacher model id, student-base model id)
PAIRS = (
    (
        "qwen3_4b_to_bert_base",
        r"(a) Qwen3-Embedding-4B $\rightarrow$ BERT-base (109M)",
        "Qwen/Qwen3-Embedding-4B",
        "google-bert/bert-base-uncased",
    ),
    (
        "bge_m3_to_minilm_h768",
        r"(b) BGE-M3 $\rightarrow$ MiniLMv2-H768 (66M)",
        "BAAI/bge-m3",
        "nreimers/MiniLMv2-L6-H768-distilled-from-BERT-Base",
    ),
    (
        "qwen3_0.6b_to_minilm_h384",
        r"(c) Qwen3-Embedding-0.6B $\rightarrow$ MiniLMv2-H384 (22M)",
        "Qwen/Qwen3-Embedding-0.6B",
        "nreimers/MiniLMv2-L6-H384-distilled-from-BERT-Base",
    ),
)

# (csv method key, row label)
METHODS = (
    ("rkd", "RKD"),
    ("stella", "Stella"),
    ("cdm", "CDM"),
    ("dskd", "DSKD"),
    ("emo", "EMO"),
    ("talas", "TALAS"),
    ("geoode", r"\tablebest{GATE-KD}"),
)


def load_students() -> dict:
    out: dict = {}
    with RETRIEVAL_CSV.open(newline="") as handle:
        for row in csv.DictReader(handle):
            out[(row["pair"], row["method"], row["benchmark"])] = (
                float(row[f"{METRIC}_mean"]),
                float(row[f"{METRIC}_std"]),
            )
    return out


def load_baselines() -> dict:
    out: dict = {}
    with BASELINE_CSV.open(newline="") as handle:
        for row in csv.DictReader(handle):
            out[(row["model"], row["benchmark"])] = float(row[f"{METRIC}_mean"])
    return out


def emit_baseline(label: str, model: str, baselines: dict) -> str:
    cells = [
        f"{100 * baselines[(model, benchmark)]:.2f}"
        for benchmark in BASELINE_BENCHMARKS
    ]
    return f"        {label} & " + " & ".join(cells) + r" \\"


def emit_students(pair: str, students: dict) -> list[str]:
    # Rank each column across distilled students only.
    ranks = {
        benchmark: sorted(
            (m for m, _ in METHODS),
            key=lambda m: students[(pair, m, benchmark)][0],
            reverse=True,
        )[:2]
        for benchmark in BENCHMARKS
    }

    lines = []
    for method, label in METHODS:
        cells = []
        for benchmark in BENCHMARKS:
            mean, std = students[(pair, method, benchmark)]
            body = f"{100 * mean:.2f}"
            best, second = ranks[benchmark]
            if method == best:
                body = rf"\tablebest{{{body}}}"
            elif method == second:
                body = rf"\tablesecond{{{body}}}"
            cells.append(rf"\meanstd{{{body}}}{{{100 * std:.2f}}}")
        lines.append(f"        {label} & " + " & ".join(cells) + r" \\")
    return lines


def build() -> str:
    students = load_students()
    baselines = load_baselines()
    ncols = len(BENCHMARKS) + 1

    header = [
        "% Generated by scripts/figures/render_retrieval_15k.py -- do not edit by hand.",
        "% Distilled-student rows:",
        "% runs/main_results_talas15k_h200_gpu67_20260904-082000/"
        "all_pairs_retrieval_mean_std.csv.",
        "% Teacher and student-base rows:",
        "% runs/aux_sweeps_20260904-113834/baseline/retrieval_summary.csv.",
        r"\begin{table}[t]",
        r"    \caption{Zero-shot BEIR retrieval (nDCG@10). Distilled students report mean",
        r"    $\pm$ standard deviation over three seeds; best and second-best results are",
        r"    bold and underlined.}",
        r"    \label{tab:retrieval-results-15k}",
        r"    \tablebody",
        r"    \begin{tabular}{@{}l" + "c" * len(BENCHMARKS) + r"@{}}",
        r"        \toprule",
        "        Method & " + " & ".join(BENCHMARK_LABELS) + r" \\",
    ]

    body: list[str] = []
    for pair, panel, teacher, student_base in PAIRS:
        body.append(r"        \midrule")
        body.append(
            rf"        \multicolumn{{{ncols}}}{{@{{}}c}}{{\textit{{{panel}}}}} \\"
        )
        body.append(r"        \midrule")
        body.append(emit_baseline("Teacher", teacher, baselines))
        body.append(emit_baseline("Student base", student_base, baselines))
        body.append(r"        \cmidrule(lr){1-%d}" % ncols)
        body.extend(emit_students(pair, students))

    footer = [
        r"        \bottomrule",
        r"    \end{tabular}",
        r"\end{table}",
    ]

    return "\n".join([*header, *body, *footer]) + "\n"


if __name__ == "__main__":
    OUT_TEX.write_text(build())
    print(f"wrote {OUT_TEX.relative_to(ROOT)}")
