"""Seed-paired differences between GATE-KD and a baseline (reviewer W7 / Q5).

Reads two ``all_pairs_final_test_by_seed.csv``-style files (they may be the same
file) and prints a LaTeX table with, per configuration and per aggregate, the
per-seed paired difference, its mean, min, max, and the number of seeds with a
positive difference. Differences are paired on (pair, seed), so the sign count
is exact and no distributional assumption is made.

Usage:
    python scripts/figures/render_paired_differences.py \
        --gate_csv <by_seed.csv of the GATE-KD rows reported in the paper> \
        --baseline_csv runs/main_results_talas15k_h200_gpu67_20260904-082000/all_pairs_final_test_by_seed.csv \
        --baseline talas --label "15k corpus" > docs/latex_iclr/tables/paired_differences_15k.tex
"""
from __future__ import annotations

import argparse

import pandas as pd

TASKS = ["banking77", "tweet", "emotion", "mrpc", "scitail", "wic", "sick", "sts12", "stsb"]
IOD = ["emotion", "wic", "stsb"]
PAIRS = {
    "qwen3_4b_to_bert_base": "(a) Qwen3-Emb.-4B $\\rightarrow$ BERT-base",
    "bge_m3_to_minilm_h768": "(b) BGE-M3 $\\rightarrow$ MiniLMv2-H768",
    "qwen3_0.6b_to_minilm_h384": "(c) Qwen3-Emb.-0.6B $\\rightarrow$ MiniLMv2-H384",
}


def load(path: str, method: str) -> pd.DataFrame:
    df = pd.read_csv(path)
    df = df[df.method == method].copy()
    if df.empty:
        raise SystemExit(f"no rows for method {method!r} in {path}")
    df["Avg."] = df[TASKS].mean(axis=1) * 100
    df["IOD"] = df[IOD].mean(axis=1) * 100
    df["OOD"] = df[[t for t in TASKS if t not in IOD]].mean(axis=1) * 100
    return df.set_index(["pair", "seed"])


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--gate_csv", required=True)
    ap.add_argument("--baseline_csv", required=True)
    ap.add_argument("--gate", default="geoode")
    ap.add_argument("--baseline", default="talas")
    ap.add_argument("--label", default="")
    args = ap.parse_args()

    g = load(args.gate_csv, args.gate)
    b = load(args.baseline_csv, args.baseline)
    rows = []
    for pair, name in PAIRS.items():
        seeds = sorted(set(g.loc[pair].index) & set(b.loc[pair].index))
        if not seeds:
            continue
        for agg in ["Avg.", "IOD", "OOD"]:
            d = g.loc[pair].loc[seeds, agg] - b.loc[pair].loc[seeds, agg]
            rows.append((name, agg, seeds, d))

    print(f"% Generated by scripts/figures/render_paired_differences.py")
    print(f"% gate: {args.gate_csv} ({args.gate}); baseline: {args.baseline_csv} ({args.baseline})")
    print("\\begin{table}[H]")
    print("    \\centering")
    print(f"    \\caption{{Seed-paired differences, GATE-KD minus TALAS{(', ' + args.label) if args.label else ''}."
          " Each entry pairs the two methods on the same seed; the last column"
          " counts seeds with a positive difference. Points, nine-task averages.}")
    print("    \\label{tab:paired-differences}")
    print("    \\small")
    print("    \\setlength{\\tabcolsep}{5pt}")
    ncols = 3 + len(rows[0][2]) + 3
    print("    \\begin{tabular}{@{}ll" + "r" * len(rows[0][2]) + "rrrc@{}}")
    print("        \\toprule")
    seed_hdr = " & ".join(f"seed {s}" for s in rows[0][2])
    print(f"        Configuration & Aggregate & {seed_hdr} & Mean & Min & Max & Positive \\\\")
    print("        \\midrule")
    last = None
    for name, agg, seeds, d in rows:
        cfg = name if name != last else ""
        last = name
        vals = " & ".join(f"{x:+.2f}" for x in d)
        print(f"        {cfg} & {agg} & {vals} & {d.mean():+.2f} & {d.min():+.2f} & {d.max():+.2f}"
              f" & {(d > 0).sum()}/{len(d)} \\\\")
    print("        \\bottomrule")
    print("    \\end{tabular}")
    print("\\end{table}")


if __name__ == "__main__":
    main()
